import { IMAGES } from "@/components/portfolio/shared";

export const caseStudies = [
  {
    slug: 'luxe-commerce-platform',
    title: 'Luxe Commerce Platform',
    category: 'Web Development',
    client: 'Afri Wear Co.',
    year: '2025',
    image: IMAGES.ecom,
    gallery: [IMAGES.ecom, IMAGES.workspace, IMAGES.brand],
    summary: 'A full e-commerce rebuild that doubled online sales within two months of launch.',
    challenge: 'The client\'s existing online store had a 70% cart abandonment rate, slow load times on mobile, and a fragmented checkout flow that frustrated customers.',
    goals: [
      'Reduce cart abandonment and improve mobile performance',
      'Integrate local payment methods for the Ugandan market',
      'Deliver a premium, brand-aligned storefront experience',
    ],
    role: 'Lead Full-Stack Developer & UI Designer â€” owned the architecture, frontend build, checkout flow, and payment integration end-to-end.',
    solution: 'Rebuilt the storefront with a React-based architecture, lazy-loaded imagery, a streamlined guest checkout, and integrated mobile money payments popular in Uganda.',
    results: [
      '2x online sales in 60 days',
      'Cart abandonment dropped from 70% to 28%',
      'Mobile load time reduced from 6s to 1.8s',
      'Average order value increased by 18%',
    ],
    tech: ['React', 'Node.js', 'MongoDB', 'Stripe', 'Mobile Money API'],
    liveUrl: '#',
    repoUrl: '#',
  },
  {
    slug: 'novus-brand-system',
    title: 'Novus Brand System',
    category: 'Branding',
    client: 'Bloom Digital Agency',
    year: '2025',
    image: IMAGES.brand,
    gallery: [IMAGES.brand, IMAGES.studio, IMAGES.uiux],
    summary: 'A complete brand identity overhaul that positioned a startup as a premium agency.',
    challenge: 'Bloom Digital Agency lacked a cohesive identity. Their visuals were inconsistent across channels, weakening trust with enterprise prospects.',
    goals: [
      'Create a cohesive, premium visual identity',
      'Establish clear brand guidelines for cross-team consistency',
      'Position the agency to attract enterprise clients',
    ],
    role: 'Brand Strategist & Lead Designer â€” defined the strategy, logo system, typography, color palette, and the full guidelines document.',
    solution: 'Designed a minimalist brand system â€” logo, typography, color palette, and component library â€” guided by a clear brand strategy and voice document.',
    results: [
      '3 enterprise deals closed within 4 months',
      'First-page Google ranking for key terms',
      'Brand consistency across 12+ touchpoints',
      '40% increase in inbound inquiries',
    ],
    tech: ['Figma', 'Brand Strategy', 'Design Systems', 'Typography'],
    liveUrl: '#',
    repoUrl: '#',
  },
  {
    slug: 'fintrack-dashboard',
    title: 'FinTrack Dashboard',
    category: 'UI/UX Design',
    client: 'KGL Ventures',
    year: '2024',
    image: IMAGES.uiux,
    gallery: [IMAGES.uiux, IMAGES.workspace, IMAGES.ecom],
    summary: 'An intuitive fintech dashboard that simplified complex workflows for non-technical users.',
    challenge: 'KGL\'s internal finance tool was built by engineers for engineers. Non-technical staff struggled to use it, leading to reporting errors and lost productivity.',
    goals: [
      'Simplify complex financial workflows for non-technical users',
      'Reduce reporting errors and onboarding time',
      'Deliver a clean, progressive-disclosure dashboard',
    ],
    role: 'Product Designer & Frontend Developer â€” led user research, information architecture, visual design, and the React implementation of the dashboard.',
    solution: 'Conducted user research, redesigned information architecture, and built a clean dashboard with progressive disclosure â€” surfacing key metrics first and detailed data on demand.',
    results: [
      'Team productivity increased by 35%',
      'Reporting errors reduced by 60%',
      'Onboarding time cut from 2 days to 2 hours',
      '94% user satisfaction score',
    ],
    tech: ['React', 'Figma', 'Recharts', 'Design Tokens'],
    liveUrl: '#',
    repoUrl: '#',
  },
];
